services:
  tiendix:
    build: .
    container_name: tiendix-app
    ports:
      - "5000:5000"
    environment:
      APP_ENV: production
      SECRET_KEY: "cambia_esta_clave_por_una_segura"
      HOST: 0.0.0.0
      PORT: 5000
      MAIL_SERVER: ""
      MAIL_PORT: 587
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_DEFAULT_SENDER: ""
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./logs:/app/logs
      - ./static/uploads:/app/static/uploads
